name: k33n
favicon: null
layout_spectrum: 0.2828
typography_spectrum: 0.45825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
