name: k33n
favicon: null
layout_spectrum: 0.83139
typography_spectrum: 0.45825
title: 'Michael Keene - Designer & Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#ea00ce'
    - '#00b7db'
    - '#9d9d9d'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
